### ISSUE TITLE
Tagging track numbers '08' and '09' returns invalid argument

### ISSUE THREAD

**Issue by 9man** [jangler/taffy#1]
For example, `taffy -n 08 audiofile.m4a` and `taffy -n 09 audiofile.m4a` will fail. Strangely, tagging track numbers 01 through 07 works.

**Comment by jangler** [comment]
Thanks for the bug report. The problem was that `OptionParser` defaults to parsing an `Integer` with a leading zero as an octal number, but I don't know anyone who thinks of track numbers in octal or hexadecimal, so it always uses decimal now. The fix is in version 1.2.1, which has been pushed to RubyGems and the AUR.
